# Built-in imports
import os
import sys
import re
import argparse
from pathlib import Path

# Third party library imports
from prompt_toolkit import PromptSession
from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
from prompt_toolkit.history import ThreadedHistory, InMemoryHistory
from prompt_toolkit.cursor_shapes import CursorShape
from prompt_toolkit.completion import WordCompleter

# Local library imports
from .core import gadgets
from .core import utils
from .core import formatters
from .core import console


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="catalog",
        add_help=True,
        description="r++ gadget parser for specific instructions.",
        exit_on_error=True,
    )

    parser.add_argument(
        "paths",
        nargs="+",
        help="Paths to one or more ROP files generated by r++. Directory also accepted.",
    )

    parser.add_argument(
        "-b",
        "--bad-characters",
        type=str,
        default="",
        required=False,
        help="A string of characters to exclude in the format '\\x00\\x0a\\x0d'.",
    )

    parser.add_argument(
        "-u",
        "--unique",
        action="store_true",
        help="Filter for unique gadgets by their raw instruction sequences.",
    )

    parser.add_argument(
        "-s",
        "--style",
        choices=["plain", "python", "js"],
        default="plain",
        help="Output format style: plain, python, or js.",
    )


    parser.add_argument(
        "-o",
        "--offset",
        action="store_true",
        help="The file contains only the offset (e.g., ALSR case).",
    )
    return parser

def main() -> int:
    
    parser = build_parser()
    args = parser.parse_args()

    bad_chars = None
    if args.bad_characters:
        bad_chars = utils.format_bad_chars(args.bad_characters)

    print(f"[+] Bad characters: {bad_chars}")

    # Collect files from both file and directory paths
    file_paths = []
    for path_str in args.paths:
        path = Path(path_str).resolve()

        if path.is_dir():
            # Add all files in the directory
            file_paths.extend([file for file in path.iterdir() if file.is_file()])
        elif path.is_file():
            if path.exists():
                file_paths.append(path)
            else:
                print(f"[!] Path '{path}' does not exist.")
                return
        else:
            print(f"[!] Path '{path}' is not a valid file or directory.")

    arch = utils.detect_arch_from_file(file_paths[0])
    print(f"[+] Detected architecture: {arch}")

    catalog = gadgets.Gadgets(file_paths=file_paths, bad_chars=bad_chars, arch=arch)


    if len(catalog) == 0:
        print("[!] No gadgets available, try another module")
        return 1

    # Filter for unique gadgets if -u flag is set
    if args.unique:
        catalog.set_uniqueness(True)

    current_console = console.Console(catalog)

    style_map = {
        "plain": formatters.PlainFormatter,
        "python": formatters.PythonFormatter,
        "js": formatters.JavaScriptFormatter,
    }

    formatter = style_map[args.style]()

    current_console.start(formatter=formatter, with_base_address=args.offset)

    return 0
